/*
 *
 *     Copyright (C) 2026 Macweese <https://www.github.com/Macweese>
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package challenge.leetcode.hard.minimumDistanceToTypeAThirdWordUsingTwoFingers;

import data.lexicography.words.Attribute;
import data.lexicography.words.CsvWordSource;
import data.lexicography.words.WordProvider;
import data.lexicography.words.WordType;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

/**
 * @author Administrator
 * @Created 07:02 Sun 12 April 2026
 * @Project 3C: Competitive Coding Challenges
 **/
@DisplayName("1320. Minimum Distance to Type a Word Using Two Fingers")
class MinimumDistanceToTypeAThirdWordUsingTwoFingersTest
{
	private static final Map<String, Integer> MAP = new HashMap<>();
	private static final WordProvider wordProvider = WordProvider.builder()
		.addSource(new CsvWordSource(WordType.ADJECTIVE.source))
		.addSource(new CsvWordSource(WordType.ADVERB.source))
		.addSource(new CsvWordSource(WordType.NOUN.source))
		.addSource(new CsvWordSource(WordType.VERB.source))
		.build();

	static
	{
		MAP.put("IN",0);
		MAP.put("BEAT",5);
		MAP.put("EARN",6);
		MAP.put("HAPPY",6);
		MAP.put("DREAD",7);
		MAP.put("SORTS",5);
		MAP.put("WARIER",8);
		MAP.put("IDEALS",8);
		MAP.put("NOONLY",5);
		MAP.put("REJECT",9);
		MAP.put("PROVES",9);
		MAP.put("UNFAIR",10);
		MAP.put("TRACKS",13);
		MAP.put("DREAMED",9);
		MAP.put("WORLDLY",13);
		MAP.put("SIXTHLY",14);
		MAP.put("RADIALLY",13);
		MAP.put("IMMENSELY",9);
		MAP.put("FACIALLY",11);
		MAP.put("INNOCENCE",8);
		MAP.put("ISOLATES",15);
		MAP.put("LAVISHLY",16);
		MAP.put("EXPLODING",14);
		MAP.put("LEAPINGLY",18);
		MAP.put("PRECURSOR",12);
		MAP.put("SUBSECTION",13);
		MAP.put("CLOUDINESS",13);
		MAP.put("FLIMSINESS",12);
		MAP.put("SALIVATION",16);
		MAP.put("CONDEMNING",10);
		MAP.put("PERTINENCE",15);
		MAP.put("COLLECTION",11);
		MAP.put("PECTORALLY",17);
		MAP.put("FORGIVESPECIAL",29);
		MAP.put("INSTIGATORDIVESTMENT",30);
		MAP.put("CLATTERINGLYEXAMINED",44);
		MAP.put("PREMIERCONSTANTLYUNFRIENDLINESS",56);
		MAP.put("RECONCILEGRATIFICATIONFUNKINESSNASALLY",67);
		MAP.put("ENFRANCHISEMENTATTENDSARTICULATIONIDEAL",73);
		MAP.put("ENDOWMENTUNINTELLIGENTLYLIKESSLIGHTLYHEEDFULLY",73);
		MAP.put("PRACTICALITYATTEMPTSDISGUISEENDWAYSASSIGNSVARIABILITY",99);
		MAP.put("EXPECTINGDISCLOSEDCOMPREHENSIVENESSATTRIBUTESCAPABILITY",100);
		MAP.put("WANTONNESSEUPHORICALLYSURVEILLANCEDEVELOPEDPURSUINGNORTHWARDS",105);
		MAP.put("RETRIEVEFIREHURTTRIPLICATIONCOUNTERACCUSATIONPROBABLEGAUDINESS",112);
		MAP.put("FREESWITNESSINGBANSPERSISTENTREADILYSHINESTOMORROWFUCKEDREARMINIONLYFEARSTEMPORARILY",164);
		MAP.put("CHANGESEDITSPUNISHESPARTICULARLYRISKEDFRENZYMANKINDSERVANTQUESTREAPPLICATIONNARROWEST",162);
		MAP.put("CONCEALEDRELUCTANTWAITINGTRUSTHAGGARDLYINFERIORFOURTHLYINCREDULOUSLYCONVERTSNEPOTICALLY",162);
		MAP.put("IMPLORIGLYLIVINGFEATURINGSTRANGERUNTHREATENINGLYAGRICULTURALNASALITYLINKINGTYPESPEEDINESS",172);
		MAP.put("INSTANTLYELECTSPURPOSENEARSIGHTEDNESSASSUAGEMENTTOURSCOMMENTALONERISKARRIVINGABANDONEDCAUTION",168);
		MAP.put("EAGERERWHATSOEVERVERBALLYUNVIRTUOUSLYSTUBBORNLYINCREMENTSETSATTENDINGMIDWEEKCONTRAPTIONFOREIGN",163);
		MAP.put("TERMINATESUNREALLYHOMOGENIZATIONINTRUSIVENESSWORTHWHILEBELITTLEMENTHEALTHIERCONTEMPTPREFERINDOCTRINATION",195);
		MAP.put("BROADCASTEROVERLOOKEDFEVEROUSLYPERPETUITYSEALEDSPECULATEDDELOCALIZATIONCONSUMEHELLISHLYUNOBSERVANTLYPALELYCOVERED",224);
		MAP.put("PEACEFULLYDOUBLEDBEHAVEREQUESTINGTRANSPORTINGANXIETYCONVERSATIONALISTEXPLORESCONCENTRATESPARTIALITYTALKATIVELYWANTONLY",253);
		MAP.put("CONVENIENTLYFETCHINGIMPUTABLYUNCORDIALLYCHAOSAMOUNTSTEMPERAMENTALLYDOUBTINGUNQUESTIONINGLYPROFITEDALIKEREPROVINGLYCORRESPOND",232);
		MAP.put("CONSTITUTEDRAGLINEARLYTAUGHTDEVELOPINGLINKCIVILIZATIONIRREVOCABLYELEMENTALLYHOPELESSLYDISENCHANTMENTLOVELYDEVOTIONREWARDINGLY",240);
		MAP.put("BENIGNLYINTERRUPTERVULPINELYRAVENOUSLYLUXURIOUSNESSPURPOSELYIMPRACTICALITYOLDNESSNASTIERDESTRUCTIVECATHOLICLYFERVORIDOLIZINGLY",251);
		MAP.put("QUIZZICALLYREPROACHFULLYINFLAMMABILITYINVOLVEDRUININGSUFFICEUNQUESTIONABLYDECLARESRECOVERSTRUSTSINSTILLATIONBARENESSINTERCEPTION",246);
		MAP.put("SHAPESVALUATIONALLYUNDIRECTLYCONSIDERAPPRECIATIONREINSTATEMENTBLEAKLYJAGGEDNESSDISCHARGINGADMIRABLYCOURTSHIPZESTFULLYSEASONALITY",250);
		MAP.put("DRUMMERPLEASESDEMONSTRATORREVEALEDSTOREDCONSTRUCTSZIGZAGGINGLYPUZZLINGLYMISERABLEENCOMPASSMENTONCOLOGISTACCUSATORIALLYVARYUNCERTAINTY",251);
		MAP.put("EFFORTLESSNESSTESTABILITYDIRECTDENSITYLYRICISTBELIEVABLYCONSTITUTINGCONSERVATORYBUILTROUNDSCOPESECTIONEXPOSINGEXHAUSTIONSEARCHEDMARCHESSLIPPERINESS",277);
		MAP.put("EDUCATORBOUNCESBOTANISTWHIMEXTRADITIONDRIVENLEVELSRASHLYUNWELCOMINGLYREALIZECHEERSCONSERVATORSHIPCONVENTIONVULNERABILITYPRIMEVALLYNIGHTMARISHLYHANDILY",327);
		MAP.put("GREETINGEDUCATIONALWRETCHEDNESSSUFFICETIPSDEMANDEDSTRUCKINVISIBILITYDENOMINATIONINTEGRATESDESIGNDEIONIZATIONTRANSLATEDGAYERCHALLENGESHIFTINGSUEDRELEVANT",282);
		MAP.put("QUEASILYANTIFASCISTINFLUENCESALERTNESSVOLCANOLOGICALLYCONTEMPORARYDAMAGINGRULEDBIZARRENESSPRESENTEDUNIFORMITYSUGGESTEDCLASSIFIESCEREBRALLYRISKINESSPRETTILY",299);
		MAP.put("TRAPPEDNARROWLYINTENSEINHIBITEDREACHINGBEHAVIORALLYACCESSINGRESPONSEFEASIBILITYSUCCEEDSLABORATORYRIDSECUREPOSSESSORCUTDOMINATESODIOUSLYEVASIVENESSINCIDENTALLY",301);
		MAP.put("CONTINENTALFLOATINGLYUNPREDICTABILITYPARTITIVELYDISTASTEFULNESSOCCUPATIONFLEETINGLYDETACHMENTVERIFIABLYUNDESIRABILITYTRAPPEDAUTHORIZATIONEXCITABILITYORDEREDREVERTING",318);
		MAP.put("WARNINGMEANINGFULLYSTUDIEDNORTHWARDCRUDESTSPARESWEATHERALREADYPUNGENTLYQUERIMONIOUSLYMERCIFULLYGREWDISCIPLINARIANUNHAPPIESTOBEYEDCALMLYTRANSFORMINGENTANGLEMENTAMBLINGLY",335);
		MAP.put("NORMALITYVARICOSELYDELETINGCHALLENGEDRETIRINGFLOATINGGISTUNWANTEDDREAMEDTRANSLATINGWELCOMINGBOOKFALLENEPISCOPALLYNONVIOLENCEHONOURINGSACRILEGIOUSLYCOMELYBASEDSTIPULATOR",327);
		MAP.put("DRIFTSMATHEMATICALGRABSOWECOUNTERACCUSATIONBOORISHNESSABEAMRIDSFIERCERELSEWISETRANSCENDENCEATTRIBUTIVELYFIRMERVIGILANTISMUNINTELLIGENTLYPROCESSEDBUSHINESSTECHNICIANSKILLFULNESS",327);
		MAP.put("WONDERSDAMPESTCONTRACTBENEFICIALLYCLUNGHOMECONDUCTORIGNORANTLYLEGITIMATEHARDINVISIBLEWINCINGLYUNHAPPIESTDESIGNATIONACCULTURATIONSTRAIGHTFORWARDNESSRECIPROCITYPREVIOUSLYFABULOUSLY",340);
		MAP.put("RETRIEVESLANDWARDSPREGNANTPRODUCERINDUCESPROVENIENCEREPLACINGVISITINGMAGNANIMOUSLYCENSORSHIPBOOKBOUNCINGLYINGENIOUSNESSPLANSRESCUESLOFTILYLUSCIOUSLYDELETIONSAMEALLOWINDIGENOUSNESSREMORSE",364);
		MAP.put("SLIGHTPREMATURECRITICISEINIMPROVINGFROLICLYPLATITUDESTHIEVISHLYINTERESTEDMASTERLYINTERVIEWNOXIOUSLYHEADSDABBINGLYTENDERESTFIRMNESSFUMIGATORUNRELIABLYIDENTIFYINGASSIGNMENTCORRUPTORWRONGFULLY",361);
		MAP.put("DISRESPECTWEAKENINGTHANKEDABRUPTLYGUARANTEEDTIMIDITYUNFEELINGLYRULEDGRADUALNESSTEENAGEVIRTUESTASTELESSNESSRESISTEDPRESENTISOLATEDLYSWINGSRAVINGLYIRKSOMENESSOUTDOORSBOASTFULNESSVALUABLEOBVERSELY",382);
		MAP.put("REGARDHEREDITYFLAGRANCECOINCIDENCEPROCESSEDSYNCHRONICITYUNACCOUNTABLYRECONNAISSANCEREVISINGALLOCATESBEATSSHARINGIMPERIALISTRESPECTIVEFIERCELYCONTRADICTIONANTIFASCISTMASSIVEHANDSOMEIDENTICALQUARTERLY",373);
		MAP.put("MEASUREINDENTATIONENGAGEDEVIDENCEBABYISHLYIMMEDIACYOUTERLYBOHEMIANPLAUSIBILITYCHEAPERDESERVEDLYSUPPORTEDOPTINGMATUREDSPECIFICATIONGRANTORBURNINGUTTERLYINDIVIDUALCALLOUSNESSDETRIMENTALCOHOLISMIGNOBLYDAREIRREFUTABILITY",424);
		MAP.put("INTEGRATINGSIMULTANEOUSLYCOMMENDATIONCADDISHNESSINCIDENCETRANSFORMINGOPPORTUNELYSTATICDISCONTINUITYUNOBTRUSIVENESSASHAMEDBARESTENDURESVILLAGEWARDSCHANTFOURTHEQUALITYASKEDCONVERTSMODERNFAMILIARISOLATEAGILITYWEIGHSLIST",426);
		MAP.put("VIRTUESCONCEALSMENTIONSTOUCHINGSOMETIMESSWAPPINGMONITORINGLOFTINESSPROTAGONISTHEADCOOLSLONESOMELYCOMPACTEDLYOBEISANTLYMISPRONUNCIATIONNEONATALLYDOCTRINALLYRUSHPRIVATELYPROTESTGLASSILYFIRSTLYMANAGEDUNTRULYDECIDEDLYARGUEFRENZYINVESTIGATOR",456);
		MAP.put("TRITENESSABOMINABLYCRYSTALLIZATIONWAILINGLYFIXESLAGLYDEPENDSATTRITIONSORESTWITNESSANTECEDENCEAVERAGESPARERDIRECTIONREFLECTINGVICEREGALLYAGGRESSIVENESSBRIEFERGUSHINGLYZAPPILYNORTHEASTERLYPRODUCTIVENESSPANTINGLYDRIFTSCOMPETEDVOYEURISTICALLY",467);
		MAP.put("PUNCTUATIONCOMPAREDSTORYTELLERUNITYDISBARMENTDEGENERATELYUSUALLYENQUIRINGLYMULTIPLEPOINTEDTRUCKERTHREWEXPORTATIONSHRIEKINGLYTHIRDSTERILITYMIGRATIONIMPORTANTLYINCREASINGCHANNELIZATIONBIODIVERSITYEXPLICITLYREPAYROTATIONULTERIORLYNERVINESSVARIABLY",485);
		MAP.put("UNPLEASANTLYLOYALINVESTIGATESINCONSIDERATELYCOLLAPSEDNUMEROUSLYFULFILLEDHOSTAGONARROWERFAILSWHATSOEVERSUSPECTSLOWINGDIPCONSPICUOUSLYDRINKSCRIEDBUREAUCRACYGUILTINESSCOMPROMISEADJACENTLYLENGTHIERFINISHINGCONSTITUTIONALITYBEAUTIFULNESSSYSTEMATICYOUNG",490);
		MAP.put("MERITEDLYFICKLENESSCURRENTLYMONOTONYROLLAPPEAREDREALIZECOGNATIONDESIRESBEDAZZLEMENTSPRINGCONSUMEDDISTURBINGPUGNACITYBRINGSAFELINGUISTRAVENOUSLYCORROSIVENESSUNOBTRUSIVELYLINGUISTICALLYJUXTAPOSITIONSCRUPLESTRACKSVEHEMENTLYSHOWEDSEMIRETIREMENTVIGILANTLY",502);
		MAP.put("FEMINIZATIONSENSIBILITYSPOOKINESSLINGUALLYQUARRELSOMENESSDEMANDINGVELOCITYBAROMETRICALLYQUARRELSOMENESSBREEZINESSFATALBAREBELLIGERENTLYATROCITYVASTNESSSPECULATEDTOWNWARDSCONGESTIONCOMPLEXANTIDEPRESSANTTECHNOCRACYMURMURSUPPORTERRUEFULLYREBUILDSMOBILITY",489);
		MAP.put("FIERCENESSSHOPPERLOBBYISTBINOCULARLYFEMINISTLIGHTSINSISTINGCORRUPTIONDISSOLVEDFLITTINGLYCAMPAIGNINGBLAMINGFIGURINGCOMMANDERSHIPPOLITICLYPARTITIONHOPELESSLYREHABILITATIONDEFERENTIALLYTORMENTINGLYWHISTLYFRANKLYDOUBLINGLIFTSARRANGELIBERALWILDNESSALLOCUTION",459);
		MAP.put("TINIESTPROBLEMINTERRUPTEDILLUSIVELYRETALIATIONANALYSEDSPLITSDISBELIEVINGLYSERVANTSUPPORTERAMPUTATIONCONDEMNSSUBSTITUTESVIRTUALSUBSCRIPTIONNONATTACHMENTGRANDPARENTLOWERDRUMMERUNMERCIFULLYTOLDSMOKINGFATLYUNAFFECTEDNESSPROVINGASKEDHIDEOUSNESSATTACHINGDETECTS",456);
		MAP.put("DESPAIRINGLYPEDIATRICIANUPPISHLYWEAKLYDROWNEDVENERABILITYPOTENTASSESSESRESTRICTOCCURRINGDERIVESDISTRUSTINAPPROPRIATELYWONTEDLYCOMPANIONSHIPEMBEZZLEMENTPROPORTIONINACTIVITYFAVORNONRESISTANCEANGEREDNIFTILYSMUGNESSMERGELIVELINESSOVERLOOKSRUBSUPPORTIVEMIRACULOUSLY",492);
		MAP.put("SECURELYANTICIPATEDLOWLINESSLEARNERINSURGENCENONPAYMENTWARDENSHIPMASTERLYDROPSPARITYLETHARGICALLYFLAGRANTLYINCOHERENTLYSYMPATHIZERREPREHENSIBLYSEEGIVINGALERTINGBRAVESTGUILTIESTATTACKPOSITIONSEPARATINGDONATIONREDNESSPSYCHOLOGISTPLURALLYMUSICALTALLESTSTAREWARRANTED",522);
		MAP.put("PERIODGIVINGREFERRERDIAGNOSTICIANLAUNCHEDDRINKGIGANTICALLYDISAGREEBOTANISTUNSETTLINGLYCLEVERTENANTSILENCESTEPCONVENIENTREALIZINGFULSOMELYTRIBULATIONCOMPREHENSIBILITYEASTERNPRECURSORDIFFICULTYCAPACITYCONSIDERATIONCARSICKNESSBITDILAPIDATIONTAUNTINGLYSECULARLYSANENESSMATRIMONIALLY",535);
		MAP.put("FUTILITYGLASSILYCHARACTERIZATIONJOCULARITYDISADVANTAGEOUSNESSIDEOLOGICALDISCLOSESMAXIMIZATIONKNOWLEDGEABLYVALOUROUSLYDISCOLORATIONUPGRADESMILITARIZATIONUNACCEPTABILITYHOBBINGLYSAYINGARISENLONEIMPOUNDMENTMILITARISMRESIDENTIALDIGESTIBILITYKINDNESSDENTISTBOYISHLYLUCKILYPROOFEXCELLENCE",546);
	}

	@Test
	@Timeout(3)
	void minimumDistance()
	{
		for (Map.Entry<String, Integer> entry : MAP.entrySet())
		{
			final String input = entry.getKey();
			final int expected = entry.getValue();
			final int actual = MinimumDistanceToTypeAThirdWordUsingTwoFingers.minimumDistance(input);

			String message = String.format("Test failed for case:"
					+ "%n%10s : %s"
					+ "%n%10s : %s"
					+ "%n%10s : %s"
					+ "%n%10s ",
				"Input", input,
				"Expected", expected,
				"Actual", actual,
				""
			);

			assertEquals(expected, actual, message);
		}
	}

	static private void generateTests()
	{
		StringBuilder stringBuilder = new StringBuilder();

		for (int i = 0; i < 55; i++)
		{
			int maxWordLength = ThreadLocalRandom.current().nextInt(299) + 2;
			StringBuilder word = new StringBuilder(wordProvider.query()
				.attributes(Attribute.STANDARD)
				.random()
				.lengthBetween(1, maxWordLength)
				.get()
				.toUpperCase());

			IO.println(word);
			while (word.length() + 10 < maxWordLength)
			{
				word.append(wordProvider.query()
					.attributes(Attribute.STANDARD)
					.random()
					.lengthBetween(1, maxWordLength - word.length())
					.get()
					.toUpperCase());
			}

			stringBuilder.append(String.format("MAP.put(\"%s\",%s);%n", word, validate(word.toString())));
		}

		IO.println(stringBuilder.toString());
	}

	private static int getDistance(int p, int q)
	{
		int x1 = p / 6;
		int y1 = p % 6;
		int x2 = q / 6;
		int y2 = q % 6;
		return Math.abs(x1 - x2) + Math.abs(y1 - y2);
	}

	private static int validate(String word)
	{
		int n = word.length();
		int[][][] dp = new int[n][26][26];
		for (int i = 0; i < n; ++i)
		{
			for (int j = 0; j < 26; ++j)
			{
				for (int k = 0; k < 26; ++k)
				{
					dp[i][j][k] = Integer.MAX_VALUE / 2;
				}
			}
		}

		for (int i = 0; i < 26; ++i)
		{
			dp[0][i][word.charAt(0) - 'A'] = 0;
			dp[0][word.charAt(0) - 'A'][i] = 0;
		}

		for (int i = 1; i < n; ++i)
		{
			int cur = word.charAt(i) - 'A';
			int prev = word.charAt(i - 1) - 'A';
			int d = getDistance(prev, cur);

			for (int j = 0; j < 26; ++j)
			{
				dp[i][cur][j] = Math.min(dp[i][cur][j], dp[i - 1][prev][j] + d);
				dp[i][j][cur] = Math.min(dp[i][j][cur], dp[i - 1][j][prev] + d);

				if (prev == j)
				{
					for (int k = 0; k < 26; ++k)
					{
						int d0 = getDistance(k, cur);
						dp[i][cur][j] = Math.min(
							dp[i][cur][j],
							dp[i - 1][k][j] + d0
						);
						dp[i][j][cur] = Math.min(
							dp[i][j][cur],
							dp[i - 1][j][k] + d0
						);
					}
				}
			}
		}

		int ans = Integer.MAX_VALUE / 2;
		for (int i = 0; i < 26; ++i)
		{
			for (int j = 0; j < 26; ++j)
			{
				ans = Math.min(ans, dp[n - 1][i][j]);
			}
		}
		return ans;
	}
}