/*
 *
 *     Copyright (C) 2026 Macweese <https://www.github.com/Macweese>
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package challenge.leetcode.easy.shortestDistanceToTargetStringInACircularArray;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * @author Administrator
 * @Created 06:34 Wed 15 April 2026
 * @Project 3C: Competitive Coding Challenges
 **/
@DisplayName("2515. Shortest Distance to Target in a Circular Array")
class ShortestDistanceToTargetStringInACircularArrayTest
{
	private static final Map<Input, Integer> MAP = new HashMap<>();

	static
	{
		MAP.put(new Input(new String[]{"hello","i","am","leetcode","hello"},"hello",1),1);
		MAP.put(new Input(new String[]{"a","b","leetcode"},"leetcode",0),1);
		MAP.put(new Input(new String[]{"i","eat","leetcode"}, "ate", 0),-1);
		MAP.put(new Input(new String[]{"aa","aa","aa","aa","aa","aa","bb","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa"}, "bb", 20),7);
		MAP.put(new Input(new String[]{"aa","aa","aa","aa","aa","aa","bb","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa"}, "bb", 12),6);
		MAP.put(new Input(new String[]{"aa","aa","aa","aa","aa","aa","bb","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa","aa"}, "ab", 12),-1);
		MAP.put(new Input(new String[]{"reaffirmation","housed","overall"},"reaffirmation",2),1);
		MAP.put(new Input(new String[]{"yummily","collapsed","clarification","corporate","publicly"},"publicly",3),1);
		MAP.put(new Input(new String[]{"contributes","flees","firstmost","commercially","moderately"},"firstmost",4),2);
		MAP.put(new Input(new String[]{"historically","urbanely","enquire","dusk","loafer","climatologist"},"dusk",6),3);
		MAP.put(new Input(new String[]{"overzealousness","genuineness","changelessness","pulled"},"overzealousness",1),1);
		MAP.put(new Input(new String[]{"surgical","acknowledge","granularly","blissfulness","regards","reluctance"},"regards",2),2);
		MAP.put(new Input(new String[]{"prevent","aim","amateur","fightingly","imitation","marketing","asunder","depression"},"amateur",3),1);
		MAP.put(new Input(new String[]{"crosses","admittedly","witlessly","venerably","imbalance","fervently","aristocracy","disappears"},"disappears",8),1);
		MAP.put(new Input(new String[]{"vively","correct","retail","unhaltingly","mortally","fellowship","disinformation","vibration","irregularity","assigns"},"assigns",8),1);
		MAP.put(new Input(new String[]{"threateningly","binds","indigenous","foolhardiness","livelily","evocation","same","simplemindedness","manfully","calculates","salaciousness"},"manfully",8),0);
		MAP.put(new Input(new String[]{"smelling","hypnotically","damning","pretending","magnificent","hideousness","tenser","minionly","hurting","virtuously","hypnotist","pretends","caused","finest","fine","rhetorically"},"finest",1),4);
		MAP.put(new Input(new String[]{"like","temporary","helplessness","fit","unnecessarily","visitor","struggles","participantly","penance","comprise","low","huskily","notify","entertained","transformed","prayerfully","harmfulness"},"prayerfully",16),1);
		MAP.put(new Input(new String[]{"kill","wearing","qualification","rests","unflinchingly","neologically","artfulness","theory","goofily","opposite","virtue","alarmedly","outspokenness","estrangement","closely","detonation","justly"},"detonation",15),0);
		MAP.put(new Input(new String[]{"attempt","wanderer","horrifyingly","caddishness","excludes","transporting","pardonably","piteously","variably","merged","transparently","xerophytically","impose","credibility","big","ringingly","easement"},"credibility",9),4);
		MAP.put(new Input(new String[]{"continuance","dating","remarkably","sentience","drain","old","associates","bafflement","contentedness","buying","hedonistically","forms","innocent","generousness","coped","planned","loading","spotted","forgetfulness"},"coped",4),9);
		MAP.put(new Input(new String[]{"apprenticeship","atomic","majestically","inappropriate","administer","magnificence","elected","delightedly","influential","welcome","foolhardiness","degradingly","deep","commands","quasistatically","imposingly","complied","triumphantly","vitally","younger","resistance"},"resistance",1),2);
		MAP.put(new Input(new String[]{"reliance","charity","lighting","profligacy","back","illustrates","linear","interlacement","garishly","distastefulness","emphasize","librarian","implication","reduce","florally","bindingly","sibilantly","cries","waited","overgeneralization","entered","secondly","own"},"interlacement",10),3);
		MAP.put(new Input(new String[]{"impose","suction","brown","drain","sorcerer","maternity","likely","unkindly","sheepishness","edgingly","fights","lack","interlacement","delegation","serviceability","catching","purposely","destiny","mean","trusting","pontificator","upwards","hiding","sensing","depravation","xenogenetically","highest"},"delegation",21),8);
		MAP.put(new Input(new String[]{"exhibitor","won","like","frees","raises","surrenders","prosecutor","today","recruit","fastness","direction","odd","oafishly","daintiness","preconception","progressively","subscribing","wrongfulness","debatingly","unknowingly","salutation","whim","emanation","encompassment","contrasts","offer","misstatement","meaningful","reelection","harmfulness"},"today",23),14);
		MAP.put(new Input(new String[]{"hotheadedness","unionization","manifestation","woken","melt","deliberately","step","luminously","knightly","supplies","vestally","hoggishly","adjectively","yellowest","reinforcement","tumultuously","resentment","relegation","applicant","level","hurrying","surrenders","regulated","plan","abstention","trashily","nominal","organising","awareness","rightly","stretches","cynicism","afforded","appeal"},"organising",13),14);
		MAP.put(new Input(new String[]{"flakily","denotation","established","hopelessness","impurity","woken","incrementally","dips","ruddily","injection","flatteringly","endangerment","charitably","irritatingly","vaporizer","reviews","embitterment","traded","indirectly","wealthily","impliedly","miscalculation","unwittingly","randomly","resulting","flexible","goofily","harmonially","preserving","emptier","resistivity","subjectivity","visual"},"flexible",9),16);
		MAP.put(new Input(new String[]{"journalist","afresh","surrogacy","exhalation","intolerance","cohesiveness","procrastinator","speeds","antioxidant","reflecting","undoubtedly","live","nittily","hunting","hypersensitivity","handle","continued","obliviousness","youthfulness","optical","drive","indulge","spell","answer","expressively","junction","pleases","bourgeois","dangerous","meeting","yappingly","plainest","laboriously","overestimation"},"optical",17),2);
		MAP.put(new Input(new String[]{"transience","dematerialization","win","disguised","functioned","redevelopment","rebuilds","see","agitator","hospitalization","plutocracy","protestor","talkatively","frivolity","valerian","sheepishly","shallow","dense","snap","conditionality","trendiness","appreciation","quinarily","desirability","inspecting","verdantly","cessation","immensely","shed","deliberation","upset","sentence","evolutionary","interacted","fool","fonder","unaccountability","anatomically","townward"},"see",32),14);
		MAP.put(new Input(new String[]{"allowing","administrator","over","praisably","lithely","ordering","shutting","hit","illustrated","atmostphereically","alienation","repaid","relative","crisply","includes","unsurprisedly","spilling","reconfiguration","spins","sticking","examining","inaccurately","conforms","lonely","sad","trade","discourteously","concrete","gratefulness","combination","strange","diagnostician","scorn","reinstallation","doubled","throng","evenly","wrily","openheartedness","neutrally"},"combination",30),1);
		MAP.put(new Input(new String[]{"distance","perceptiveness","herein","equator","baldly","suspects","builder","zestily","criminality","compete","legislative","glancingly","recklessness","simplicity","tenser","creditor","elected","recurrently","entailment","nervousness","profession","consistently","tap","indicates","initiated","urging","prosecution","wooziness","intrusiveness","adulation","negotiating","understood","splitting","numinously","movement","roominess","prowess","melts","boilingly","reconciled"},"intrusiveness",28),0);
		MAP.put(new Input(new String[]{"external","modifies","varies","decieiveably","risks","mindfulness","coder","pose","evolutionary","insists","neutrally","pestilence","grace","constituted","entrancement","unemployment","spunkiness","shipward","disenfranchisement","solicitation","obscure","echoes","allocate","cared","matches","fact","fiercer","straightforward","thriller","inevitably","entertainingly","undeservingly","dingily","nonchalantly","endure","frying","enslavement","weepingly","forward","merit","reproduces"},"decieiveably",15),12);
		MAP.put(new Input(new String[]{"makes","tuggingly","financial","suspend","entailing","rustily","approached","sentience","meaningfulness","motionlessness","hired","orchestrator","frivolity","grandness","shaped","punitorily","tormentor","cut","genially","corpulence","excludes","hurtfulness","wetly","distinguishes","coached","contractual","fractiously","behaves","curves","deducibly","torridly","moment","possessed","horrible","perfection","evolvement","hungriest","heavyheartedness","deceivingly","voracity","lower","comprehensibility"},"wetly",21),1);
		MAP.put(new Input(new String[]{"germination","existed","publicist","prone","tips","dipped","nutritionist","transcendentally","ruder","conservatively","wondering","storminess","services","encouragingly","willfulness","nutrition","linguistically","continually","ghostliness","optimally","stabilization","mystification","landward","thoroughly","ailment","attain","equation","goodness","unfairly","lovingly","utility","discovered","express","gained","nonappearance","vigorously","glassily","survived","blows","ambitious","dismantlement"},"encouragingly",20),7);
		MAP.put(new Input(new String[]{"twirlingly","faddishness","translucently","extinction","discontinuance","undergoing","inactivity","comment","hardheartedness","unwillingly","expecting","hypocritically","remedially","fetching","bewilderedness","turning","luminescence","applicability","owe","antiperspirant","dominate","condescension","capably","adverser","breeziness","reacting","ambiance","hedonistically","imagining","delayed","endured","negotiate","tofore","nobility","steeper","vicariousness","qualmishly","encirclement","laconically","beats","ample","space","posingly"},"tofore",23),9);
		MAP.put(new Input(new String[]{"kinship","commerciality","disengagement","most","surround","detecting","won","overdependence","crispness","wake","heads","adjacently","eventfulness","contemplates","crankiness","vaporization","sorts","retrieves","sympathizer","frozen","descends","disassociation","crept","vendor","advantage","stimulate","consignor","penmanship","concludes","instructorship","defibrillation","considering","risked","numberlessly","cleaned","use","save","allegiance","logicalness","atrociousness","nonresistance","oppose","gossiper","steadier","frequently","profitably","punishes","installing"},"surround",36),16);
		MAP.put(new Input(new String[]{"homelily","test","glowingly","masculinity","newest","metamerically","broken","internship","misclassification","insubordination","atomic","investor","delay","impartially","capitalization","roughness","gratefulness","enduring","corruptibility","baptism","snaps","disintegration","files","instructing","salesmanship","forgave","creating","exploded","objected","functionally","randomness","whimperingly","latterly","told","anxieties","grotesquely","stoic","sailor","kinder","peasant","drunk","dissipation","male","referrer","pertness","recently","refrainment","service","crossly","musicologist"},"corruptibility",36),18);
		MAP.put(new Input(new String[]{"desegregation","warrant","relatively","softly","unaffectedly","tidily","forward","indigence","rancidly","postulation","argues","hidden","lasts","windingly","dissolved","virtuosically","searchingly","overtly","ranging","wanted","prudishly","crunchiness","outerly","clearing","remobilization","weest","palely","otherwhere","authenticity","callousness","visigothically","enjoyable","efficiently","completeness","leveled","surrender","repentance","volunteerism","bigger","wistfulness","unobservantly","proceeding","care","shakily","flashingly","presumed","overtreatment","sold","lastingly","tenderer","resourcing","possessor","yummily"},"relatively",50),5);
		MAP.put(new Input(new String[]{"susceptibility","distraction","married","claiming","conceivability","perspicuously","celebrity","musicologist","musicianship","predictably","require","surefootedness","plagiarist","cooller","lawfulness","perceptively","spends","trains","concludes","reconsider","downstairs","local","threateningly","maidenly","fulfilling","travels","normally","burden","seems","reforestation","similarly","yielding","contradictor","colorblindness","prepare","northeastwards","freshness","recentness","denigration","wishes","pleasantries","beyond","speculator","sternness","minionly","stems","occurs","commutation","passive","fight","seemliness","frequently"},"colorblindness",30),3);
		MAP.put(new Input(new String[]{"adheres","pomposity","proof","fresh","induced","stoic","clear","included","containerization","parallel","sappily","mistily","relaxingly","inhibits","kiss","illegally","differentiates","rebuilt","reproduced","innocently","fluffily","daily","emotionlessly","listener","quote","efficacy","accuser","navally","calligraphist","dirtiness","reinstatement","cinematographer","impliedly","belongingness","lushness","rid","prospective","snobbishness","campaign","unreliability","victor","softened","runs","varyingly","together","detainment","inadequately","certainly","vocalization","tropically","legitimate","hyperactivity","demonstratively","pratingly","loyal","glance"},"emotionlessly",40),18);
		MAP.put(new Input(new String[]{"childly","telling","independently","aided","rushes","booking","schemingly","cleaner","popped","parenthetically","helplessness","variability","very","satisfaction","scoring","waved","inexperience","crashed","westward","separating","coerciveness","judged","drowned","concreteness","fixatedly","gentleness","grumpiness","instructor","adulation","unpopularity","reduced","modulation","sedition","overpayment","watchfully","services","horizontally","taken","interrupter","alleviate","globally","outgoingness","final","hopingly","videoconference","gladiator","attain","correcting","professional","obeying","drives","gravest","mere","forecasts","supremacy","tragedy","gentlemanliness"},"drives",12),19);
		MAP.put(new Input(new String[]{"cheerful","replying","past","trades","lifting","ensuring","deliver","hyperawareness","augmentation","righteously","gruffness","dialectically","hard","star","relegation","gnashingly","obey","consisting","huskily","justify","stressing","renews","yeomanlike","describe","sneer","granulation","consignment","maymight","slightest","protect","demonstrated","collapsed","unhappiness","saves","puzzlement","bamboozlement","outline","forecasting","predict","specialist","bareness","eighteenth","trustfulness","mastery","frumpily","persuading","fervor","favor","removability","hilariously","vitally","strongly","inheritance","purification","excellently","fooling","hangs","directory","reputably","fetched","dullest"},"favor",39),8);
		MAP.put(new Input(new String[]{"hang","unsociability","challenging","defeatism","achieves","monopolization","rankness","omnipotently","flammability","defacement","practitioner","imperativeness","mistrustingly","dull","surprising","digital","trendiness","confronts","friendly","aimlessness","majestically","trivial","adsorption","protects","sikerly","warmed","facility","locked","fabricator","basic","encourage","dimply","causal","explored","tactlessly","deportment","demands","fretful","posture","approximation","ungainliness","aggravation","dwelling","based","persists","negotiate","computerization","reserving","brushed","symbolism","optimization","oxygenation","heavy","forcing","wheezingly","desirable","endangerment","triviality","peculiarly"},"improbably",2),-1);
		MAP.put(new Input(new String[]{"guaranteed","governorship","giftedness","corroboration","imply","due","hurts","deserve","inhibitor","pausing","installation","steal","equation","scratches","nobbily","accumulating","orator","aim","demands","disaffiliation","criticise","award","withdrew","rose","bothers","detention","preserves","flatulence","restricted","qualmishly","fullest","amend","manage","refusing","entertaining","susceptibleness","drained","wonderfulness","positions","removability","leveling","heavy","spend","broadest","worthy","pursuing","occupant","troublesomeness","concede","calms","successive","flakiness","contribution","underutilization","scarifyingly","oiliness","wrap","compaction","investigation","warningly","suspend","shamefacedly","excludes","tastelessness"},"demands",18),0);
		MAP.put(new Input(new String[]{"developing","transmittance","supplies","migrant","unguardedly","deciding","value","hits","zygotically","representative","insatiably","minionly","converted","still","attribute","freakishly","dissolve","innocence","looked","deliverability","direct","shifted","substitute","financial","doubt","incident","republication","depended","throbbingly","diametrically","viceregally","revolutionary","diminishes","front","bounces","clever","virtues","alleviate","live","hatefully","shall","guides","gloweringly","hungriest","nerviness","recorded","deserved","counterargument","ruled","implicitly","ineffectiveness","janitor","mortally","unsparingly","former","rarer","closed","conveyance","spiritual","handsomeness","double","befittingly","conciseness","triumph","smile"},"innocence",13),4);
		MAP.put(new Input(new String[]{"viability","allocated","surest","worry","mixtly","pleadingly","absenter","friskiness","prays","variably","waveringly","deep","assembling","meet","maturity","power","wordily","actually","patently","go","engagingly","unsightliness","agrees","boiling","measurability","excludes","dear","punctuation","delicately","closeness","develop","developed","shutting","worthiest","owned","buried","venally","pulls","herein","probability","mutually","ones","coaches","remotely","enquire","theatrically","meridionally","reticence","guidance","contrasted","senatorship","fosters","delightedly","dips","allocation","trickeries","universality","emerged","shallowness","unfairness","jealously","entails","firmly","orthodox","warmness","complained","wail","musicality","seasonal","outstanding"},"absenter",1),5);
		MAP.put(new Input(new String[]{"denigrator","reader","formulating","liveliness","attendance","similarity","unclearly","ratification","stiffest","homeliness","enormously","containing","getting","presence","contributed","gothic","hopes","paleontologist","dismantlement","seasonably","ungenerously","drop","see","verbal","avoids","fosters","femininely","thanks","readably","attributed","lets","examining","infinity","reception","facing","impurely","exploration","irresistibility","nonpayment","faithful","alerts","mighty","enclosed","oneness","plaguily","evacuation","germanely","hating","gayly","venture","terror","commenced","helpless","blackest","painlessness","tailor","trivial","disguise","continuousness","anonymity","prosingly","cheapness","oral","incapably","comfort","flat","lethally","modally","bioluminescence","florally","infestation"},"plaguily",6),33);
		MAP.put(new Input(new String[]{"educate","identity","ascertainment","effectually","systemization","strongest","complains","positively","slowing","fresh","exact","implements","collector","notifying","headed","enshrinement","burn","conferred","abidingly","reserves","blown","jestingly","illustrates","pausing","collapses","expressed","unavailability","transcription","insecurity","origination","obscuring","rectory","friendly","condemnation","obsoletely","softens","importunely","vaguer","philanthropist","shifts","bleak","windingly","outdoor","irresponsiveness","optometrist","mentioning","rankly","comprehensive","manifestly","vigorous","featured","yeastily","loudest","hairiness","devaluation","carnally","intended","deferentially","illegally","noumenally","collected","theorist","urbanization","shall","luxuriousness","pinned","impossibility","varyingly","ruling","chastely"},"loudest",43),9);
		MAP.put(new Input(new String[]{"stare","sanction","vary","chastisement","formulated","wraps","southern","undeservingly","chased","shallowest","barriers","catching","palest","manufacturing","whiggishly","surround","dear","corruptibility","slowness","honouring","requests","dense","flavor","unsubtly","shifting","visionarily","praises","dissatisfaction","prolongation","narcissism","lopsidedly","consignment","level","daintily","bloodiest","amicability","process","sickness","seedily","yestereven","salinity","enclose","nightmarishly","saintliness","sorrowfulness","vibronically","votively","invariably","resigns","finish","protestant","coolness","screams","merging","quasilocally","securing","ultimate","translucence","ghoulishness","tutor","illusiveness","saves","degradingly","voraciously","aims","inhalation","casualness","retentively","firing","continuity","attainment","otherwhere"},"voraciously",24),33);
		MAP.put(new Input(new String[]{"accountability","skinniness","nasally","kind","justly","modifies","undernourishment","strangest","zymographically","needs","lingually","convinced","luminosity","gregariousness","unrevealingly","congratulated","finality","gurglingly","building","rested","flourish","narrower","extending","close","net","definiteness","civilization","adapts","slipping","unscrupulously","pretending","reforms","bitter","appeals","wontedness","delicately","fancied","protective","misclassification","balanced","erotically","directs","availableness","consent","direct","dependability","fry","peripheral","insanely","gullibility","unkindness","recognition","leaning","outburst","nutrient","endearment","brotherhood","influenced","cheapness","deferment","resource","miserliness","dependableness","regulating","rows","located","meantime","participator","astrophysicist","resulted","adversity","growlingly","absorbs","antiracist","demands"},"slipping",21),7);
		MAP.put(new Input(new String[]{"eaten","instructing","conforming","peripheral","repay","routinely","impetuousness","underwent","tighten","malignantly","dressing","penitently","ardor","irresistibility","finish","endlessly","drain","innovation","initiation","mechanically","clumsily","yestermonth","dinginess","matches","beliefs","affection","antiracist","stoic","quailingly","pathos","shutting","broader","address","communicativeness","magisterially","manipulation","survivorship","stillness","sung","reputedly","released","emulation","live","backwardness","prior","east","propitiously","survivability","punishing","infinity","invariability","ghastly","lightheadedly","important","hilariously","comfortableness","first","variation","fermentation","hatefully","identicalness","reserving","navigably","poorer","worthlessly","drive","eloquently","shows","fetisely","centeredness","circumstance","vengeably","litigant","metallization","talent","falsest","forecasting","venerability"},"finish",5),9);
		MAP.put(new Input(new String[]{"update","appreciating","expedition","gather","funeral","operating","trying","offensive","waving","unsmilingly","keep","rustily","nakedly","dominate","accurate","superintendent","condemn","hanging","guiltily","protection","uprightness","unrevealingly","discusses","meddlesomeness","tolerantly","sudden","classically","checks","operation","thunderingly","debatingly","ships","win","result","protested","unreliably","leaned","impertinence","replenishment","freer","shallower","easing","looser","duplicator","immaculacy","deception","dancing","intuitively","annihilator","ulteriorly","extraordinarily","drop","devotes","obviously","confirming","criticism","identically","dejection","endearedly","looked","establishing","enunciation","too","presentation","wildness","placation","evidentally","height","honor","renovation","overcomes","scrutiny","guesses","views","oversoon","proceeding","employability","tale","passionate","sticking","lustfully","listing"},"dancing",81),35);
		MAP.put(new Input(new String[]{"attended","federacy","dirtily","pointed","sees","complies","eruption","evenly","affords","witily","flexibility","antiracist","brighter","defamation","recalling","warns","unreceptively","loosest","never","tardily","postponed","coordinates","cancel","ticked","proper","definitively","protector","sky","dug","rimosely","formed","trying","annoyance","xerically","ferociously","tenaciously","purgatory","devoting","laziest","adventure","overdevelopment","destination","importantly","remorselessness","honouring","recognises","cryptically","impingement","neglectfulness","verification","legalistically","spiritually","livelier","upgraded","failing","memorably","fighter","gainfully","mess","volumetrically","wiping","obviousness","denser","numerally","scoffingly","unresponsiveness","mode","raise","barometrically","dazzlingly","reasonability","ineptitude","cheater","propitiously","trinity","trivial","tracing","postproduction","disposition","correct","familiar"},"unresponsiveness",76),11);
		MAP.put(new Input(new String[]{"assigning","exerting","sameness","period","belatedness","impliedly","mode","endure","hominess","junction","freelancer","stylishness","disagreeing","enunciator","minding","caring","beauty","closeness","erroneousness","resembled","numerously","packs","impoverishment","varies","sometimes","briskness","virtuosically","exactness","flittingly","missed","zestfully","hopes","owe","freakishly","impudence","futileness","sulkiness","forgiven","promptness","reactivation","expanding","wholeness","ordinariness","cancel","glowingly","conciseness","neat","pretended","variant","filing","assumption","distributor","jubilation","correspondent","outlandishly","glamorously","resourcefulness","essentially","governance","inception","purchasing","bleakly","unswervingly","supervise","where","prospective","slipped","protectant","irrevocably","lifeless","silly","dug","acquisition","obsequiously","says","icily","swallowed","informal","resiliently","warfare","upward","inquisitor","socially","embark","attempt","riotously"},"minding",43),29);
		MAP.put(new Input(new String[]{"observantly","arrogantly","primarily","clockwise","corroboration","rushes","hated","legibly","undergoes","experimented","provokes","approve","organizational","chivalrously","trinity","vacillation","reverses","acute","smugness","othergates","swarthiness","empathizer","glow","bears","rumor","reduces","departmental","essence","barely","operate","must","odder","east","yellower","defender","award","extra","quickwittedly","tantivy","blindest","bragger","worthlessly","warrantor","surefootedness","wonderfully","escapades","lordship","entrepreneur","oddity","project","content","point","appropriate","despondently","airsickness","supply","suing","resigning","guiltiness","replies","intelligently","assistance","coordinator","terminating","specification","kindheartedness","settle","venously","bold","vicinity","civilian","activism","caddishness","irradiation","broader","grandness","unhelpfully","nonparticipant","invites","concede","covertness","patient","lasted","rosily","unreluctantly","irrationally","suspiciously","specialist","consternation"},"swarthiness",73),36);
		MAP.put(new Input(new String[]{"presidential","cried","demanding","consolidated","decimation","engagingly","evangelist","jocularity","marginal","filmmaker","strive","entail","employment","conductibility","gradual","providently","visual","languishingly","voraciousness","wittily","inexistence","included","arrange","overtime","discriminate","correspondent","compensates","segment","recertification","inhibited","pick","disbelievingly","wailingly","conformist","forgetfully","receptionist","paying","mentality","straightforward","fears","terrifically","painful","replies","whiningly","traditionalism","backwardness","inspires","weakness","accounts","counterintelligence","told","live","regrets","warmness","softer","ceases","paramountly","quaffably","neglectfulness","lividly","eternity","naturally","immaculately","openhandedness","knowledge","skepticism","financing","benevolence","opportunity","reasonable","doubtful","fishes","troublesomeness","same","virulently","arrives","aesthetician","overcoming","smooth","replacement","inserting","possessing","awkwardly","terminate","toughly"},"eternity",43),17);
		MAP.put(new Input(new String[]{"access","northwardly","denigration","nonsocially","enter","quintessence","smoothly","half","matches","universal","entertaining","sensationally","creator","protests","inadequate","maymight","attending","called","reverts","inexperience","undignifiedly","radical","premonition","charity","permissively","biodiversity","mummification","look","alter","asunder","abridgement","illustrating","inquisitively","studentship","bohemian","potentially","thinks","absorbedly","yawnily","conceived","decidedly","trueness","moviedom","warfare","floating","hopelessly","microbiologist","twentieth","makes","depressurization","entirely","deplorableness","pendently","unbecomingness","aptly","raucously","hyperparathyroidism","unaccountably","livelier","handsomely","began","filminess","objectification","bodily","ludicrousness","petty","vexedly","dangerousness","zoomorphically","sunny","holding","differ","finances","inaptly","difficulty","arrests","arrives","adeptness","masters","heftily","intolerability","pursuing","hastily","criticises","redeployment","quantumly","confliction"},"protests",45),32);
		MAP.put(new Input(new String[]{"hoping","religiously","awaiting","overestimation","luminously","then","magnetic","stepped","multiplying","visibility","disconcertment","confliction","concentrated","hibernation","fiscal","identical","hungriness","antioxidant","reapplication","illustrates","northern","allowed","heading","entirely","slides","inwardness","hilarity","thermally","awarding","grantor","establishing","formidable","passively","funding","shows","inspectorship","manipulated","stocking","retrospectively","opportunity","lawlessly","exchanged","animator","failed","armament","worker","exactly","sweetness","experiences","predictor","overcompensation","reminding","extracted","conveys","worthiest","fierceness","maladjustment","gastroenterologist","rankness","recurrently","pressed","constructing","remedially","proctor","specialist","misfeasance","discontentedly","prominent","shimmeringly","theocracy","aware","wants","differently","euphorically","sustained","interment","mandatory","dissatisfaction","election","retires","station","froze","smoothness","torturously","related","objectiveness","strange"},"interment",15),27);
		MAP.put(new Input(new String[]{"handles","approached","divided","estrangement","saved","discusses","properly","belittlement","spot","adapting","heftily","registers","pursuance","joy","consolidated","fat","stocked","tailor","queerishly","victor","eventual","encountering","enjoyment","circumstances","local","regimentation","painfully","calming","conventional","pulsation","departmentalization","told","indecisively","invention","undoubtedly","lead","bravely","quinarily","largeness","praising","promptly","maternity","importunely","burst","richness","damages","warns","read","invincibility","supplier","expressiveness","offsetting","hanging","compensation","convenient","gayly","pleasantries","cooperation","agitator","distortion","renders","infiniteness","atomic","required","moral","flourishing","combine","blest","controlled","snap","imposes","replaced","face","sounder","community","apostleship","tonelessly","omnipotence","supermajority","sufficiently","enforced","maladjustment","prevention","sweetly","creative","dislikes","litigation","sponsorship","draw","unguardedly","result","meekly","thoughtlessly","point"},"burst",35),8);
		MAP.put(new Input(new String[]{"withdrew","sorting","closer","convention","ominously","puerilely","sunlight","theorist","confronting","serenity","similarly","serviceability","dejectedly","brushing","syntactic","opaquely","handicap","hopes","love","extraordinary","infraction","aim","appeasement","rapid","lower","illustrating","discourteousness","chronic","rearwards","vociferously","inferior","baked","lowliness","lobbyist","publish","unsettlingly","decontamination","clerkship","unfortunately","exactly","spunkiness","said","tone","sibilantly","noisiest","metaphysically","historically","annual","quincuncially","thuggishly","wistfulness","neuroticism","trickeries","recommencement","mispronunciation","faith","debatingly","principally","artistic","earnestly","storyteller","vitally","corruptness","scream","tightfistedness","performance","detector","youngness","education","foolhardiness","laughableness","boldly","protestor","weer","proceeding","dentist","entail","zingily","tenant","subsequent","reconsiders","increasingly","fighting","protested","president","isolationist","posterity","comments","confront","fold"},"preemption",82),-1);
		MAP.put(new Input(new String[]{"organisational","yestermonth","compliment","customization","regulate","schemingly","flexible","pointedly","horridly","defibrillation","implicitly","formation","eruption","precedence","impartiality","abandon","richly","colorfulness","floridity","revoltingly","permanent","fearing","separately","achievement","courteousness","reflecting","fandom","listed","fragrantly","meddlingly","deliberate","banging","feels","overexertion","gleefulness","reverence","sorrow","diversity","squarest","masterfully","neatest","fails","gracefulness","roundly","verification","list","organised","penalization","walking","anxious","seemed","jauntily","painting","trepidation","reverentially","coarseness","indigestion","reenactment","measly","atonement","unflappability","whatever","lone","weepily","cartographically","thenadays","domination","quackishly","contend","opposed","awesomeness","grew","bursting","internalization","insidiousness","witlessly","hung","establishing","buy","love","desperation","abolished","magic","protecting","agent","sardonically","disengagement","slammingly","cankeredly","borrowing","sheer","praising","seen","differentially","primitive","fairer","hesitating","mounting"},"precedence",46),33);
	}

	@Test
	void closestTarget()
	{
		for (Map.Entry<Input, Integer> entry : MAP.entrySet())
		{
			final String[] words = entry.getKey().words();
			final String target = entry.getKey().target();
			final int startIndex = entry.getKey().startIndex();
			final long expected = entry.getValue();
			final long actual = ShortestDistanceToTargetStringInACircularArray.closestTarget(words, target, startIndex);

			String message = String.format("Test failed for case:"
					+ "%n%10s"
					+ "%n%10s : %s"
					+ "%n%10s : %s"
					+ "%n%10s : %s"
					+ "%n%10s"
					+ "%n%10s : %s"
					+ "%n%10s : %s"
					+ "%n%10s ",
				"Input",
				"Words", Arrays.toString(words),
				"Target", target,
				"Start IDX", startIndex,
				"Output",
				"Expected", expected,
				"Actual", actual,
				""
			);

			assertEquals(expected, actual, message);
		}
	}
}
record Input(String[] words, String target, int startIndex)
{

}