name: Other
description: Open an issue regarding something else
body:
  - type: markdown
    attributes:
      value: >
        ## 3C issue

        Before proceeding to submit an issue, please verify the issue
        is not a duplicate of an already exist issue in the [#issue
        tracker](https://github.com/Macweese/3C/issues). If your issue
        is found to already exist, please provide any information to the relevant issue
        through a comment or a reaction.
  - type: textarea
    id: textarea-1
    attributes:
      label: Issue description
      description: Please provide additional, thorough details about the issue.
        Issues with poor descriptions or lacking information are less likely to be reviewed or resolved.
    validations:
      required: true
  - type: textarea
    id: textarea-2
    attributes:
      label: Motivation
      description: Please motivate why this is an issue, and why changes need to be made.
    validations:
      required: true
  - type: textarea
    id: textarea-3
    attributes:
      label: Screenshots or recordings
      description: Add any screenshots or recordings related to the issue.
    validations:
      required: false