/*
 *
 *     Copyright (C) 2025 Macweese <https://www.github.com/Macweese>
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package challenge.leetcode.easy.countTheNumberOfConsistentStrings;

import data.lexicography.words.Attribute;
import data.lexicography.words.CsvWordSource;
import data.lexicography.words.Word;
import data.lexicography.words.WordProvider;
import data.lexicography.words.WordType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.Consumer;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * @author Administrator
 * @Created 05:36 Tue 18 November 2025
 * @Project 3C: Competitive Coding Challenges
 **/
@DisplayName("1684. Count the Number of Consistent Strings")
class CountTheNumberOfConsistentStringsTest
{
	private static final Map<Map.Entry<String, String[]>, Integer> MAP = new HashMap<>();
	private static final WordProvider wordProvider = WordProvider.builder()
		.addSource(new CsvWordSource(WordType.ADJECTIVE.source))
		.addSource(new CsvWordSource(WordType.ADVERB.source))
		.addSource(new CsvWordSource(WordType.CONJUNCTION.source))
		.addSource(new CsvWordSource(WordType.INTERJECTION.source))
		.addSource(new CsvWordSource(WordType.NOUN.source))
		.addSource(new CsvWordSource(WordType.PREPOSITION.source))
		.addSource(new CsvWordSource(WordType.PRONOUN.source))
		.addSource(new CsvWordSource(WordType.VERB.source))
		.build();

	static
	{
		MAP.put(Map.entry("cdfgjloqstuwy",new String[]{"trained","proximally","fully","more"}),1);
		MAP.put(Map.entry("bcefhknpqtuvxy",new String[]{"regains","bloody","ministers","visibility","originator","guided","snaps"}),0);
		MAP.put(Map.entry("acfhmswxy",new String[]{"preferred","strictly","inwardly","shipping","remembered","sneer","pleaded","ravingly"}),0);
		MAP.put(Map.entry("acdefghlmoqsvw",new String[]{"juiciness","attempt","temptedly","fumingly","fired","overcome","restively","novelist"}),0);
		MAP.put(Map.entry("adghijmnoprtuwx",new String[]{"recruits","strategist","satisfying","teaching","weer","perdition","withdraw","relative","northerly","standard"}),1);
		MAP.put(Map.entry("abcdefhlnopqrsty",new String[]{"cash","fits","encounters","reparably","may","managed","dictates","interest","fact","past","near","totality","like","tediously","enquiring"}),5);
		MAP.put(Map.entry("abcefgijklmntuxy",new String[]{"geniality","drearily","tolerated","bending","arguing","variedly","differ","murders","requesting","ideally","riskiness","fastly","files","witticism","rich"}),1);
		MAP.put(Map.entry("bdhijlmoqtuvw",new String[]{"known","busier","winds","noting","gaspingly","insert","achieves","dresses","irrelevant","actor","angrier","alive","firsthand","stickiest","nationally","directly","leniently"}),0);
		MAP.put(Map.entry("acghijlmrswxy",new String[]{"satisfy","home","large","fished","opts","reunitedly","owe","brushed","needily","compete","unfair","climb","pleasure","must","speed","publicity","pollinator","trap","contending"}),0);
		MAP.put(Map.entry("abdefijmnopqtuvwx",new String[]{"singer","townwards","barriers","exceed","for","boiling","forgives","living","splitting","obtaining","begs","attracts","sophist","treated","creepiness","estimated","allocates","coach","attacks"}),0);
		MAP.put(Map.entry("aefgklmnprstvwy",new String[]{"fall","pursuance","vacantly","generality","admires","slowly","balloonist","sorrow","compulsory","irrigation","shortness","decorates","tauntingly","steering","living","hypnotist","zealously","compatible","himself","ridicule","peaceably","dissension","ceasing"}),1);
		MAP.put(Map.entry("cdfghinqtwxy",new String[]{"functioned","dear","endeavor","depart","devote","notorious","trickiness","noticeable","together","lends","confident","selected","abundance","hypothesis","uses","unequally","isolates","northward","given","dearly","faced","denigrator","opinion","furiously","plugs","strictly"}),0);
		MAP.put(Map.entry("begjmrstuwx",new String[]{"saved","forgiven","swang","relieving","sticking","indicated","laughing","charmingly","reputably","boyishly","gracefully","geological","impossible","opposite","tristfully","but","glacially","raffishly","pointedly","approve","thinking","forward","light","dared","weekly","share","anger"}),1);
		MAP.put(Map.entry("cefghijkmoqvxy",new String[]{"prepare","belongs","fishes","hereablout","vainness","where","whoa","closing","stocks","develop","creditor","inside","forcefully","estimably","beyond","zappily","migrant","defector","observance","step","base","creeping","develop","widen","following","levelly","behaves","damage","supplies","commonly","renews"}),0);
		MAP.put(Map.entry("bcdfijmsty",new String[]{"pursuing","remittance","naw","thorniness","result","foamingly","formal","testiness","coziness","finest","bluer","negotiator","adhere","care","inside","lieutenant","impureness","disuse","sequence","stress","coinciding","eaten","warmest","desired","relying","hissingly","works","endure","came","desire","defilement","admitting","tiny"}),0);
		MAP.put(Map.entry("adefhijlqtuvy",new String[]{"inned","breeziness","polarity","waifishly","replacing","noisiness","usurpingly","trick","unctuously","contempt","monotony","stickiest","tipsily","hah","teetotally","counting","finances","poured","sensed","performs","affecting","announce","thrust","dear","socialist","aberration","notionally","differed","obscure","delete","eighteenth","knocking"}),2);
		MAP.put(Map.entry("abcehimqrtvx",new String[]{"frontally","pour","dominate","sensing","nobody","courtship","trading","concern","whitest","zzz","violently","chucking","inspects","directing","greeted","fast","possible","barer","dips","voguishly","served","cope","rarely","frowningly","unnear","toughly","whereas","pollution","ripely","filed","smallest","solitude","trivially","embarked","focally"}),1);
		MAP.put(Map.entry("cdflnoqstvw",new String[]{"promisor","national","pungently","summons","mimically","temporary","competence","gassiness","warrantor","anxiety","knits","guard","eliminate","guardian","success","replied","dismisses","obtusely","descends","sixth","elect","plainer","corrected","swimmer","fails","statement","sentiments","thornily","as","upright","slily","halfway","defines","affluence","lie"}),0);
		MAP.put(Map.entry("bceghjknpsuxy",new String[]{"veriest","waywardly","alas","whatnot","shininess","athlete","flight","swift","skepticism","denseness","commercial","ignoring","equator","pretend","total","slanderer","inhibits","wontedly","worrying","causation","snap","likability","excitement","emolument","musical","everyone","poetically","finance","retires","condemned","mean","sheds","purveyance","doctorally","schemingly","criminal"}),0);
		MAP.put(Map.entry("abcgijlmpqvwx",new String[]{"freeing","chorally","intervene","cruel","lightly","capability","defender","touring","community","partition","shiftiness","pride","quantity","fumigator","genetic","naturally","staying","drifted","severely","vicinity","usurpingly","losingly","ropily","chucked","retaining","debility","beginning","evidently","sizably","figures","overall","burn","peevishly","arresting","broad","decide","implicitly"}),0);
		MAP.put(Map.entry("cdfgklmnpqrtvw",new String[]{"skimpiness","mental","narrow","one","zoologist","preferred","theocracy","drop","glibness","retention","pull","adopt","faintly","gamely","exploiting","urges","disclosing","viscerally","incubation","emotion","agreeing","enquiring","jump","pensively","initial","constant","utility","deaf","consume","sealed","snap","cheap","handling","legal","unlawfully","retrieving","send","mankind","purple","heads","opt"}),0);
		MAP.put(Map.entry("bcfiknopqtuvwy",new String[]{"each","purposedly","rawness","named","managing","formulated","future","mind","shopper","grateful","trapping","regardless","calm","reasonable","suffering","consulship","rockiness","doggedness","reserve","sacredness","plumpness","postponing","decimally","dedicator","atonement","solitary","assess","alikeness","nihilism","haggardly","obtuseness","appointing","helpless","detecting","jaggedly","innocently","ideal","losing"}),0);
		MAP.put(Map.entry("cflnqry",new String[]{"sanitation","innocence","graduation","relieve","electively","efficient","optional","regulating","easement","griminess","inventor","prosecutor","glaringly","portrayal","looks","covertness","withdrew","none","inspection","hazily","opposite","mediocrity","telling","valerian","directer","redemption","believed","reliance","divinity","sarcasm","kingdom","disciple","obedience","creeping","exerted","strain","culturally","haltingly","parked","sexual"}),0);
		MAP.put(Map.entry("bcdehijmnprsuvw",new String[]{"searched","feminine","else","witness","variably","collapse","adhered","brave","preserving","supplies","than","judaically","expressing","machining","lift","contracted","fast","stimulates","after","naval","jantily","placidity","allegedly","slimmer","noted","sereneness","racily","does","arctic","decryption","perception","vexation","chirpingly","buys","taxed","inherit","fastest","retrieves","touchedly","addiction","standing","opacity","newfangly"}),1);
		MAP.put(Map.entry("abdfgijloqrstx",new String[]{"unseldom","droppingly","extortion","glad","pettiness","protestant","processing","ready","announced","reputably","dull","prevail","valued","engages","correct","enactment","funniest","syndicator","confirm","indolence","nonpayment","considers","ovally","expertise","saturation","gather","advisably","gee","plugs","viscously","otherwhere","surrounds","fickleness","exhibition","pronely","wetness","vengeably","loneliness","toxically","screaming","everyone","won","suspend"}),1);
		MAP.put(Map.entry("acdehiklnoqrstu",new String[]{"brilliance","publish","direct","tiniest","glumly","forcibly","fraternity","apart","ruder","fellow","horsepower","briefest","lack","won","tiresomely","paying","subject","referrer","showing","narrower","relies","perpetuity","doubtful","undertakes","explicitly","flashiness","gravely","hung","fulsomely","as","finality","banning","femininely","dirty","definition","dared","striven","triumph","stipulator","exchanging","prospect","lazier","excellence","imitator","matching"}),8);
		MAP.put(Map.entry("abdfgjmqsuvwx",new String[]{"us","helps","catering","linguist","crept","imposition","yogically","possesses","lovelier","ceasing","tangibly","adoration","spoiling","washes","refusing","telephoned","succeeding","qualify","modally","terminally","confluence","yikes","knitwise","fadedly","lo","pick","sunk","say","judaically","dream","murdered","unhappier","feeling","mockingly","left","goes","vagally","barbarity","loudest","essential","offsetting","mirth","fears","worthy","scornfully","accounted","odder","shops","requested"}),1);
		MAP.put(Map.entry("bdefgjklopqrsuvxy",new String[]{"mirth","cooking","creatively","explores","subject","tour","bleak","bake","ordering","waving","rightly","pityingly","helpfully","initiated","friendly","emptiness","inherently","undirectly","interim","designing","consist","ascertains","instructs","cold","spring","zest","speculates","exposed","swap","tutorship","or","colours","loads","sensuously","plead","seemed","sole","inviting","postponing","blamed","pomposity","lain","vacantly","deservedly","ceased","equally","absolutely","divorced","several","spot"}),5);
		MAP.put(Map.entry("abcdgjknpstuvx",new String[]{"twitchily","audacity","awarding","wonderment","steepness","wiggly","adjust","convention","humbleness","agreed","anxious","tender","steers","ticking","engaged","conduct","abduction","primarily","toured","uniform","wrap","conceive","entail","hurts","redder","flimsiness","connect","vigorously","tolerance","nosiness","desires","licitly","somebody","resolving","indebtedly","priced","absentest","navigator","motive","usurpingly","buy","preemption","ourself","impresses","machinist","trait","egads","grim","deterring","hopes"}),1);
		MAP.put(Map.entry("adeijloqrvw",new String[]{"testiness","whenever","commuter","monetary","producer","answer","surviving","wrathfully","tip","faultiness","wateriness","electrical","improve","breathe","results","quoting","abandoning","mightier","lawlessly","placidity","drollness","gay","belong","advising","rises","praisably","stand","polarity","numerably","tutorially","anymore","goes","latterly","above","linking","overly","timed","phoned","attitude","singer","stolen","excellent","managed","underneath","discover","commence","orders","rancidly","blissfully","swallowing","multiply","voluntary"}),0);
		MAP.put(Map.entry("afgjmnprstuwx",new String[]{"extracting","contended","replied","effecting","invest","dear","precursor","values","right","fleeing","mighty","affection","allusions","trapped","gigglingly","nooo","sedation","creativity","contention","amounted","goodness","swimming","natantly","confers","searching","suits","expedition","jumped","squeezes","poignantly","run","greyer","premier","liquidly","pestilence","outermore","special","vivider","dismissing","relaxingly","arguably","injustice","leftwardly","equal","twitchily","realizes","foe","apishness","acceptable","race","equator","alienation"}),1);
		MAP.put(Map.entry("abcdefghilorstvx",new String[]{"only","tighten","horrible","stickiest","charges","badly","visit","roundly","elusively","pleasantly","cheerful","integrate","eviction","lack","going","trusted","unhappier","distortion","partially","preference","fighter","limpingly","evenly","bareness","vote","uncannily","darkness","amazingly","predation","intensity","excluding","neonatally","alas","someone","nattily","damned","fanciness","rightfully","postponed","shops","soapiness","blessedly","activist","position","watched","deep","footsteps","abstractly","promised","enormity","cost","surrogacy","puerilely","aerialist"}),9);
		MAP.put(Map.entry("bdfjklmnpqstvy",new String[]{"accuser","reassure","seems","pompously","farther","fumigation","compact","retired","hungriness","haziness","repairing","facing","heftily","moderately","viewlessly","psst","apart","collapsed","break","server","smile","recruited","while","ministered","idea","ovation","going","temper","broker","crazy","suck","weakening","protestor","color","herself","propaganda","slows","no","worrying","profound","warmth","denial","encouraged","term","polewards","moodiness","announce","thank","argue","before","swam","inequality","dilution","breeziness","railingly","glowingly","chirpingly","soften","dream"}),1);
		MAP.put(Map.entry("bcefklmopqsy",new String[]{"overlooked","grumpiness","blackness","it","licitly","political","detecting","prolixly","outragedly","accurately","patly","stealing","appear","years","yestertime","astuteness","yearlong","formulate","contract","brushing","puts","guidance","optimally","postponed","nasality","folly","through","exploded","engaging","rests","softens","summons","tsk","swum","hurts","create","continuing","selfishly","repugnance","torridly","each","suspended","happens","growing","rigidly","promoting","fastly","devoted","planted","diverting","creation","neat","gaddingly","summon","dusk","warms","discharges","glance","fit","inspecting","apishness"}),1);
		MAP.put(Map.entry("dfghklnuv",new String[]{"positivity","regularity","rules","induction","nicely","greets","wordily","forecast","pruriently","enjoy","missed","slackly","overmore","doubtless","only","exhibited","skill","jovially","risibly","lasts","ease","martially","inward","amateur","says","fascist","deserves","exposed","coloured","promises","eachwhere","freezing","dependent","summoned","very","reply","relieved","nuclear","throwing","took","moreover","pacifist","hear","tracks","remedies","drains","benefactor","fit","won","way","divert","riotously","frightened","commander","zzz","polite","filminess","like","resources","mortician","above","mounts","wooden","feature","lucidly","incredible","dense","calmed"}),0);
		MAP.put(Map.entry("acdefghjlmotwy",new String[]{"shitfully","viperously","switches","visitation","plainest","theirself","passed","doubling","derived","mood","wore","offer","nobbily","sickest","packs","desolation","unclear","awake","conductor","radiantly","us","propaganda","ethnic","viscidly","counter","humanely","deception","emulator","fostered","illness","intense","counselor","ablest","rightward","vibration","misery","own","mellowness","ancient","devote","place","waved","locking","sereneness","sorting","suspend","passed","lived","watch","management","supposed","resigned","criticises","all","carefully","exchanging","awful","emulation","enhance","builder","gracious","politician","parfitly","slipped","exterior"}),3);
		MAP.put(Map.entry("cegijkmopqrstwy",new String[]{"volitively","emerging","tie","fancied","forgive","podiatrist","damage","adding","nightly","sordidness","expanded","offsets","cleaned","sleeping","presents","bend","basic","accumulate","seller","papally","conceives","fair","opposite","required","attempt","stood","grievance","ick","cloudiness","violation","unreadably","away","recreation","retrieved","lets","unpleasant","abilities","woefully","fished","silence","bright","glacially","violetward","boredom","attends","chiefly","stipulator","meanwhile","restricts","navigation","affliction","advance","decreased","superb","vocatively","persuade","geoscience","migrator","stating","divergence","owe","reduction","joyously"}),5);
		MAP.put(Map.entry("bcefghjlmrwy",new String[]{"collapsed","hypothesis","himself","where","while","reunitedly","tearingly","withdrawn","brevity","strive","studies","sturdiness","faculties","fucked","succeeding","conveyance","care","primly","reaching","practises","communist","habitually","rolled","servitude","convinces","criticises","adhesively","jerkily","imagery","ranged","pageant","swang","vulgarity","leveled","switch","bluely","liquidity","heat","combine","oral","whose","satisfying","whoso","angrily","hated","commander","toward","cleverness","vacation","drowsiness","only","difference","sit","kapish","slickly","couth","invite","service","yestertime","waywardly","massively","fucks","laughs","trustingly","vernally","scrutiny"}),1);
		MAP.put(Map.entry("afhjmnopvwxy",new String[]{"urbanely","friendly","abstention","human","vividly","competing","exchange","owner","smile","about","navally","propellant","cares","roaringly","worrying","orator","fitter","round","certain","inspecting","various","majority","eeriness","persistent","mildness","criticised","plainer","friday","tabulation","inducement","gay","said","tamely","governs","describe","export","displays","hopelessly","hawhee","thrusting","extract","more","yummy","icily","capacity","assembling","proceeds","records","abolishing","questward","feminist","partiality","rejected","discover","initial","disrespect","longest","worriedly","masters","empty","hibernator","services","midweek","nah","fulfilled","disunity","arises"}),1);
		MAP.put(Map.entry("diklprtuwxy",new String[]{"martially","stated","darkly","sworn","judged","daintiness","reassure","skepticism","hawhee","ringleader","lowly","agreeing","seriously","included","dreadfully","blunder","challenge","worldly","upset","substitute","notifies","shifted","feelingly","cracks","sharp","pleasure","preferring","noisier","candidness","pacifist","rare","unsurely","anymore","regulatory","minds","messiness","hellward","select","cost","transform","agreeing","drafted","front","jauntily","compares","sereneness","presence","paid","alerted","resistance","joker","decorating","reduction","do","acute","us","name","take","accurate","idly","scruples","addressing","positivity","poetically","carrying","disguising","waves","talking"}),1);
		MAP.put(Map.entry("dfghikloprsvx",new String[]{"lives","haltingly","onwards","alliance","entail","wealthily","basically","preparedly","pointed","points","resignedly","drifts","engagement","idea","athwart","preserving","listener","wetter","coastal","escaped","advocator","more","viable","disrupting","noway","ocularly","parks","pluckily","timed","instant","atomic","healthily","silly","harmlessly","eating","ugliest","bless","rejected","finish","tightest","moderately","telephones","wherever","shopper","translated","disturb","resemble","defines","narcissism","riches","engulfment","evil","sign","lumpiness","throughout","weakness","dear","horde","complete","quakingly","finishes","charged","expiration","amen","competes","entire","slipped","fumigator"}),0);
		MAP.put(Map.entry("cdfmps",new String[]{"clearness","races","colourful","worth","implicitly","love","causal","tawdrily","conceded","brutally","basic","inquisitor","jailor","gawkiness","solidarity","satirist","affords","spelled","nuts","gave","tasting","ask","jazzily","deleting","lexical","pregnant","fragrance","clear","queerly","project","reunitedly","occultly","viperishly","planned","cognation","bright","cries","trivial","simple","deception","exposes","prior","cashed","healthy","sufficient","flutist","testament","compared","reserve","beauty","excavation","pinkest","series","closest","heavier","unusually","reporting","intimate","placement","verily","nobly","relies","pungently","laxly","unwantedly","filthiness","delight","devise","cancelled","apart"}),0);
		MAP.put(Map.entry("bdefgijkmoqstwy",new String[]{"slowing","regularity","proportion","recluse","arborist","picked","grown","eagerly","resolutely","cures","arrives","builds","discipline","hauntedly","reflecting","market","confessing","despite","massively","pushiness","brevity","overcomes","stocking","researched","paternally","dominates","brush","tightest","deferment","swiftest","fastest","sagely","listened","flamingly","extinction","destiny","otherways","obituarily","relaxing","frees","escapades","sell","talent","exist","climbed","narcissist","abandons","voice","lispingly","clumsily","suffice","chiefly","cheering","considered","response","woke","minimally","at","springs","clearly","sponginess","tie","obtainment","presumed","worst","chased","buying","eventually","behind","inheritor"}),3);
		MAP.put(Map.entry("abcefgiklopqrsuwx",new String[]{"history","allows","informer","multiplied","blesses","lots","held","harmlessly","base","stayed","minimal","permitted","well","meritedly","revised","demolition","wait","diversity","midships","organize","enormous","boxer","recorded","biblically","gayest","wonderly","kissing","quiet","virtues","calculates","firmer","involves","absolute","wondered","peripheral","viably","train","worrying","adapt","underneath","livingly","leadership","voguishly","captures","morbidity","implicitly","evaluation","enforces","wackily","technician","mentalist","envisaging","luminously","torridness","thespian","clerkship","service","moderately","sit","desire","trueness","sense","multiply","drained","lean","processor","profligacy","guarantees","heats","punitively"}),6);
		MAP.put(Map.entry("bfhijklnpqstu",new String[]{"link","vacation","after","word","numerator","sunlight","living","falsest","ministers","drowning","formulates","maximum","pryingly","after","protected","ceases","insulation","graded","brilliant","eek","eviction","addiction","translate","hot","undertaken","conveyed","briskly","trickily","arrive","curing","indicated","corruption","consulship","shape","malice","risked","scientist","rowing","save","cautious","courtship","magic","nobility","artistic","mortality","repeating","privately","past","selfishly","oafishness","bright","made","no one","huzza","preference","looks","ridden","girlishly","tiny","churlishly","swifter","places","nicer","confusing","go","warmth","calmingly","unaware","indicates","validly","translated","viscously","show","privacy","cleans","repair"}),1);
		MAP.put(Map.entry("bcdfijmoruv",new String[]{"cheekiness","politicly","indicator","reforms","divulgence","attractor","buyer","dismay","pugnacity","popishly","rest","snootiness","rousingly","inhibited","welcoming","exclusive","absorb","waviness","tyranny","formulate","commenting","belong","admitted","challenges","exotic","weirder","but","lights","wrongfully","freedom","impliedly","ostensibly","firstly","novelly","coollest","varies","humankind","worrying","restrains","furiously","ploddingly","jumblingly","weaken","shares","reaching","diverted","report","veracity","optically","comprise","bitter","violence","dissolve","it","kingdom","brr","handicap","aid","thee","strove","impudence","accounting","tidily","invents","blocked","pulling","critical","promptness","notably","activism","ominously","ocularly","inciter","profited"}),1);
		MAP.put(Map.entry("abdhjlnqrvx",new String[]{"circularly","admire","maintained","hauntedly","breathes","most","frostily","floating","guiltily","contrary","live","inhibits","now","crashed","duly","grossness","deepness","productive","auxiliarly","accept","leaped","plenarily","answered","bans","prisoner","conversely","jubilantly","consume","allegiance","blames","diverting","lexically","rude","annually","pitilessly","haggishly","polarity","unarguably","newly","doctorally","abundance","speculator","tourism","distortion","horizontal","hence","leaps","judging","undermines","began","endearedly","oversoon","warningly","objected","trivially","rectory","brevity","dear","softly","ridiculous","got","dusk","waste","left","sturdiness","vital","fifthly","pop","pageant","recent","proving","earned","artistic","ya","foulness","evasively"}),0);
		MAP.put(Map.entry("cdefgilmpqrswx",new String[]{"destroyed","attaining","frigidity","stimulated","flashily","fragility","quaffably","strategic","gracefully","normality","jarringly","playing","fluffily","dilution","as","zero","delayed","impress","cried","fiercely","steadiness","smallest","lain","sensorily","trivially","valued","weigh","encryption","acclaim","line","evacuation","powerful","increase","cruel","submitted","traitor","sincerity","inevitable","solving","hah","fancying","inspect","full","posture","conform","loveliest","prior","aw","wateriness","poetically","premature","quickest","permitted","covering","posingly","matched","benefits","truculence","nearness","regain","though","pack","aspiration","recognised","dipped","quirkily","thank","wildest","what","donation","realism","ruddily","amends","confess","detestably"}),3);
		MAP.put(Map.entry("adefghijklnuvwxy",new String[]{"sing","repair","yearward","permanent","coldest","inspecting","advance","grievance","absorbs","ripeness","wonderly","revive","daily","exploiting","yielding","mentor","woefulness","someday","increase","achieving","exceeding","perplexity","warranty","prevalence","survey","through","punishing","seventhly","advises","none","capitalist","striking","elitist","uncivilly","forward","silkiness","alienation","difficulty","yellower","fuller","denying","hugest","stored","arranging","myself","lyricist","resembled","proposing","frighten","nettlingly","distinct","relied","unfair","caters","compensate","libelously","throatily","hang","reviving","pressed","admirably","walked","drains","zowie","after","zero","believing","attack","boosted","yuckily","sufficient","rose","services","arguably"}),5);
		MAP.put(Map.entry("abfijlmnrstux",new String[]{"meaning","clearness","joyfulness","summation","floatingly","appeared","hates","aim","hum","influenced","push","head","infection","divorces","believably","gracious","decided","flatly","comprising","contention","excitedly","impressed","pastorally","helper","launched","forgotten","festally","stirs","sizably","enough","hunting","enormously","contempt","inspired","amongst","differed","costlier","risen","hiddenly","fandom","boiling","similar","protesting","sunny","senses","auditor","remedies","optional","indicates","fragility","whomso","wise","gastric","contract","onto","crudeness","poignantly","obtained","reason","negotiate","youthfully","drives","trick","joyfulness","vainness","fluffily","shutting","daintily","unquietly","outline","vampishly","thermally","completed","exchange","officer","rusticly"}),3);
		MAP.put(Map.entry("bcdeijklopqrtuvwy",new String[]{"designs","blend","modern","prudently","aught","classify","diminished","viscidly","excuses","funniness","sufficed","whole","serves","ignorance","clean","exploiting","sold","plurality","stocking","puffingly","captures","animation","mirth","ethically","directest","discloses","state","capability","binds","rovingly","presses","withstood","as","bassist","liquid","pinker","attendance","arbitrary","oversoon","wanderer","loathingly","okay","conscious","brighter","opens","sameness","levity","indicated","gadzooks","leaped","did","feudally","swings","apply","uncannily","cheers","tsk","borrowing","damages","break","willfully","talk","dirtiness","senior","woozily","summoning","queerishly","deepness","reserve","calm","gracious","sufficient","variant","taps","illegality","step","lineage","shortest","evaluation","dominate","especially","diverted"}),4);
		MAP.put(Map.entry("bcegmnopstuvwx",new String[]{"minimalist","abolishes","mainly","again","tenderest","squalor","stemming","seemed","furthest","diverting","leave","conduct","reduced","smartness","litigator","resentment","involves","absorbedly","harshly","harassment","vandalism","depositor","given","tasting","fightingly","lot","professor","closing","eternally","arrest","pettily","hidden","defensive","tolerate","juror","open","survivor","closest","burning","verifiably","kicked","perkily","pink","unamicably","highly","numerally","carpenter","fish","abidingly","achieved","limpingly","harder","wontedness","praises","windiness","bemusement","inhumanity","immorality","war","fivefold","vaguely","deadly","swiftest","fragilely","kind","motivation","ropily","ascertain","arisen","cleanlily","wanderer","proved","low","alteration","sleep","painlessly","deserve","acceptor","along","kicked","ritually"}),2);
		MAP.put(Map.entry("bchiknqrtvw",new String[]{"interior","sanctity","traitor","civility","grant","uncleverly","preemption","glassily","yeomanlike","merely","griminess","rolled","used","ta","integrates","listed","speaker","gently","moderately","repays","oneness","fair","alter","preference","campaigned","departs","fitted","exported","urged","performing","forget","angriness","assume","whew","equation","funkiness","emolument","dealing","doubles","completion","variedly","defensive","perversely","best","issues","threaten","challenges","towards","rescued","pudginess","gently","reserve","excusing","abandon","dissident","final","slower","abeam","some","defined","physician","vacation","obdurately","calling","word","estimate","interpret","hellward","perfectly","perceived","tenseness","emerged","unnear","reveal","kindly","terribly","equivalent","quadruply","mentions","faults","who","transform","marvellous","notices"}),0);
		MAP.put(Map.entry("abcdeghijnorwx",new String[]{"producing","polluter","stayed","granting","exploded","skinnily","pressing","ladyship","then","fifth","true","youngness","otherwise","cry","combats","apologises","completion","cooling","spatial","swim","cautious","implies","toxicity","adoration","doggone","tenth","head","came","empirical","leftwardly","ultimately","wholeness","laudably","blesses","sealed","talks","limiting","vileness","apishness","fumigation","whomsoever","pleasingly","whatever","wide","interact","immorally","rancidness","recording","caused","prettiest","spins","wittily","someone","damages","fetches","adaptor","neglect","ya","thespian","expertly","tall","disrupts","irrigation","rows","reverts","managing","posed","symbol","inspects","naughtily","fatly","valuable","indulged","in","calls","down","inhibits","colonic","outermore","round","inheritor","moodiness","mild","corniness","offered","initiation"}),6);
		MAP.put(Map.entry("bcdefghijkloqtuwy",new String[]{"seethingly","thickness","wittiness","nastier","friskiness","venerably","lengthiest","underneath","liability","lineally","anyhow","yet","whizzingly","awfulness","puts","homewards","sick","othergates","shadily","fivefold","angriest","ornerily","preference","foolish","drearily","pendently","throve","subscribes","encourages","pathos","subscribe","granting","occupy","deserve","prayed","underneath","brush","kissing","bashfully","can","rottenness","allowed","heating","tamely","qualmishly","embezzler","mixtly","patiently","ignoring","finer","clammily","performer","bother","crucially","what","elasticity","dashingly","inadequacy","softer","sucking","character","spilled","admission","hang","pressly","surrenders","swaps","known","yields","rapidness","trustily","breaking","plurally","deadly","leaves","monetary","ignoring","compatible","intervenes","ruinously","strive","separately"}),1);
		MAP.put(Map.entry("abeghjpsty",new String[]{"deleted","steps","fixt","horribly","among","hydration","each","bind","vary","westward","enviously","poorness","gamely","flautist","realness","matched","cash","migration","execute","bloody","priggishly","ran","proposed","iambically","twist","composure","boosts","squarer","hiddenly","laxly","diminished","differ","flimsiness","primness","accusing","hushedly","abutment","craftily","reticence","lifting","partition","detachment","marks","cry","grasped","blocking","foo","rigidness","heading","memory","finances","detention","admiration","virginly","loweringly","properly","hesitation","choose","pleads","thee","suits","icily","politely","offendedly","decimally","views","crazier","explains","produced","tightening","deviation","coordinate","finished","intervenes","hearlingly","foreign","brief","preventing","black","physical","instant","contending","digression","laughing","affectedly","angers"}),2);
		MAP.put(Map.entry("bdfhilmnpqruwy",new String[]{"glassiness","classiness","president","ignobly","decorating","big","zonally","machinist","karmically","profit","cloudiness","light","alone","acted","effort","sensorily","chatted","angered","virginally","intestinal","nounally","ill","downward","whosever","wailingly","flavor","fairest","calms","balanced","over","waspishly","strain","once","fancied","commercial","objection","treated","atop","debility","strict","backwardly","serviced","premier","youngest","suchlike","sacred","plagiarist","defeatist","exposed","innocent","states","murder","tale","venomously","wonderly","faith","privation","sensed","surliness","highlights","sunlight","amazingly","indebtedly","deadly","sure","hurtfully","bias","frigidly","forgave","travelling","designs","project","screamed","providence","rigidity","became","emptiness","drinks","pryingly","abreast","detention","promised","smoothly","modify","pick","throng"}),1);
		MAP.put(Map.entry("befgijnopqrstuvy",new String[]{"gastric","mature","drew","sensation","doubled","ambiguity","prophecy","genially","penitence","beggarly","damp","committing","rid","homeless","dampest","snapping","graded","wackily","dismay","hears","inasmuch","intimacy","silently","phones","expeditor","noisiest","elusively","whoops","retains","gratefully","removed","reasonable","owe","finances","acquires","plausibly","plight","presumed","yappingly","criminally","obscenely","saying","fishing","eased","overcame","ravishment","chucked","pretending","ride","vexation","forth","organic","slammingly","shoddiness","whereof","customer","edition","similarity","teasingly","inhibitor","sick","comprises","successful","thick","delicately","judgeship","glance","deliver","pratingly","manfully","morality","abloom","seemliness","closes","teasingly","restraint","remembers","ending","basically","manipulate","impalement","reflects","scarcely","encampment","defeatist"}),1);
		MAP.put(Map.entry("adghijqrsuwx",new String[]{"frumpily","ruder","wrapping","difficulty","firmly","talented","opts","noonly","entire","torment","abductor","finds","regarding","midway","gallantly","privately","force","issue","transfer","unkindly","cleverness","gesundheit","shyly","morbidly","back","pushiness","opulence","blamed","serviced","gassiness","variable","boils","grimace","notedly","above","pleasant","deleted","truth","profits","lonely","funded","protective","disciple","first","fixedly","mind","junior","clumsiness","by","gayer","condemns","foxiness","sneer","venture","blended","burden","satisfy","opens","collected","dorsally","organic","very","brotherly","sixthly","peppiness","glowingly","watch","spare","impolitely","disdain","charges","integrate","improving","behavior","needily","wear","defends","graciously","launching","outer","enduring","highlights","enhanced","zenithally","wrapped","nor","unkindness","need","vital","breathed","valid","addresses","possession"}),0);
		MAP.put(Map.entry("abgknqvy",new String[]{"levitation","telephoned","doubtless","summon","bassist","relatively","coolness","extracts","limits","eeriness","gave","awfully","topping","afterward","drinks","features","barbarity","knowing","bang","sweet","roman","restores","obedience","alerted","frightens","cancelling","niceties","continuity","impairment","queryingly","links","previously","observed","varied","placing","harms","feminist","loudness","mode","privation","seemingly","replaced","modulation","fandom","deafly","antithesis","hate","tallest","line","hobbingly","below","pollution","notation","trimness","yellower","endorse","separation","hatefully","includes","passingly","whatnot","denial","burden","completes","crisply","lastly","faction","inaccuracy","conferring","thought","wakes","stock","reconcile","largeness","redly","features","wore","picked","wary","access","demureness","tolerably","pauses","preferring","wooziness","evolve","notices","changing","outcept","she","lateness"}),1);
		MAP.put(Map.entry("adgklnqrstu",new String[]{"gratefully","frostiness","lines","infirmity","meeting","primary","chronic","infinite","chance","accusation","drunk","ridicule","frankness","nearly","pull","prevailed","zowie","fussily","reckon","descendant","poses","nah","juror","yourselves","propensity","ramblingly","sereneness","prosily","enquires","offensive","offered","adorably","rare","slimmer","selling","climb","climb","supply","traded","leaping","facing","wackiness","corrected","propellant","pulpiness","endlessly","diverting","warranting","verbosely","specific","fitly","tensest","devising","centrality","routinely","place","assess","sloppily","semblance","breaks","progresses","passionate","reversed","imposingly","rebuild","processing","tests","insurgence","profited","shop","complied","integrates","correcting","agreed","floppiness","competes","she","baldly","shininess","watching","shoots","copy","minister","presents","surrogate","privily","casually","internship","instinct","travel","approves"}),1);
		MAP.put(Map.entry("acefghjlmpquvw",new String[]{"spreads","youngness","sleepily","begun","zookeeper","yippee","expressed","physicist","zonally","reparation","supply","flowing","valuable","hitting","florally","dictates","minimally","stiff","happening","wakefully","hard","sweetness","unkindly","encouraged","ooh","doubt","alike","yearlong","obligation","around","conscience","as","protestant","ensure","inadequacy","truthfully","alien","offered","refused","respects","fear","measuring","inviolacy","printer","damned","humbly","outerly","coolness","cankeredly","truncation","we","state","myself","fleeing","guide","washing","suffers","braininess","estimated","criticises","concession","recitation","unfairness","counting","charged","stay","permit","dedication","tact","hanging","advocator","someday","services","wish","dual","clerkship","youngness","sensing","stripping","doubles","higher","lone","fill","providing","pride","optically","amazingly","imitation","oafishness","embarked","disagrees","ordinary","disposed","resonantly","agreeing"}),1);
		MAP.put(Map.entry("adgnqrstuy",new String[]{"beforehand","wimpily","sterility","backed","capitalist","plays","workmanly","transports","unicyclist","handed","creditor","requesting","spare","unduly","conform","energy","darkness","fold","jealous","costliness","verdantly","garishly","nicely","added","calming","piousness","artistry","treat","conveys","no","enunciator","abominably","declare","zonularly","repudiator","fetisely","state","arsonist","greeted","civilian","shoot","weepingly","conveyed","quiet","smelling","obliquely","audibly","closest","craft","reconciles","rare","attachment","charging","over","hit","collect","explores","quickest","endearment","yestertime","inhibit","sikerly","tautly","yeomanly","get","sticky","federation","interprets","clarify","eighthly","smooth","elegantly","fussiness","coherently","proving","balanced","host","fatality","share","slackly","general","clammily","murmur","approved","mobile","haltingly","indoors","struggles","hunting","collapses","pick","mutilation","cools","needsly","literally","classifies"}),0);
		MAP.put(Map.entry("bcdehijkoprtx",new String[]{"shakenly","wary","neatest","refused","nobleness","blonde","coauthor","surprising","strategic","exaltation","burden","suspects","northly","unguiltily","biological","selling","challenge","boyishly","secularly","alongside","comply","swapped","checking","come","tightens","traitor","trombonist","weds","dullness","clashingly","insists","privily","enables","minor","controls","requested","spoil","gentleness","shame","insecurity","unwontedly","sunk","education","engulfment","dancingly","organise","optimally","faults","implicitly","around","backed","vulpinely","honoured","knew","loading","engagement","kissing","hating","inequality","animatedly","prices","peasant","helper","classical","improperly","absurd","warily","yesterday","reticence","migrator","assessed","disbelief","location","senator","up","lopsidedly","guarantees","figment","strikes","attributes","component","fresh","productive","adjusted","preferably","manage","disturbs","coincide","printer","superior","cash","chases","thorough","please","hum","stimulates","ripeness","dedicator"}),0);
		MAP.put(Map.entry("egijoqrvwxy",new String[]{"classified","creeps","breathing","clammily","raffishly","divisional","height","manywise","feared","handy","fights","martially","terseness","greatly","washed","positioned","broke","previously","maximum","rounding","huh","honoured","ethically","zonularly","never","tackling","must","miser","including","loved","sort","thrivingly","escaped","asked","attaches","everybody","regardless","castigator","thrivingly","viperishly","hopefully","soften","greediness","glassiness","dear","affects","boarding","retrieves","handing","global","boils","yellow","wooden","premature","barring","fawningly","oppositely","designing","capitalist","easily","parking","adjustment","between","admits","costly","explained","suspending","greyer","swept","ferment","grand","rural","attack","bounce","mobile","meet","pessimist","apart","connected","illiteracy","limit","evolution","rockiness","crack","criminally","wailingly","communist","combining","accompany","elects","invalidity","emphasise","myself","leveling","enthusiasm","of","pastiness","fulfils","bass","droppingly"}),1);
		MAP.put(Map.entry("bdehjlnorvy",new String[]{"shakily","warned","barest","fascism","stranger","librarian","repression","wishes","record","national","place","interprets","commandant","submission","florist","salience","potential","excluded","capitalist","thorniness","demanding","fishes","in","equator","recurrence","rowed","defly","tearing","allocated","abolished","allegory","jubilantly","reaches","laugh","escapist","past","tax","enormously","squalor","response","ejection","tearily","angered","nomination","promotes","central","presented","unshakably","creed","grew","westwards","stylist","conducted","pleasingly","intending","resentment","notorious","claiming","suction","adjust","exerting","bizarre","learns","premature","house","prudently","emphasized","tunefully","charging","hit","connected","northwards","mediator","fullness","waits","recalls","plagiarist","kindness","associates","learned","abhorrence","rousingly","peasant","tenuously","trepidly","consists","tears","adjusts","flautist","played","tastefully","cruel","sleeps","literally","work","whereas","beneath","conquest","deflation"}),0);
		MAP.put(Map.entry("beghijklnopqv",new String[]{"stepping","gawkiness","effect","principal","scope","defeated","fell","conduct","corniness","statement","liked","either","in","ruin","initiation","secondly","important","fixation","polluter","mightier","conducts","embrace","runs","indecently","politicly","fading","obtainment","nuisance","measured","united","visitor","winding","isolation","drabness","salutation","drowned","decreasing","foe","teenage","promotion","tartness","ill","temporary","result","arranged","restrains","equity","ruthlessly","flee","frumpily","movement","implorigly","duplicity","occurred","poorness","hurries","estimated","adorably","again","vertically","bury","amendment","afterward","assumption","tamely","transport","freeing","niggardly","vanward","inevitably","territory","burning","sponginess","cartoonist","awhile","balancing","steady","spoiled","beware","reparation","direct","reserve","folds","immensely","engaged","leastwise","boredom","highest","sloppily","assurance","blending","rowed","adornment","highlights","chemist","penitence","declines","executing","variety","nature"}),2);
	}

	@Test
	void countConsistentStrings()
	{
		for (Map.Entry<Map.Entry<String, String[]>, Integer> entry : MAP.entrySet())
		{
			final String letters = entry.getKey().getKey();
			final String[] words = entry.getKey().getValue();
			final int expected = entry.getValue();
			final int actual = CountTheNumberOfConsistentStrings.countConsistentStrings(letters, words);

			String message = String.format("Test failed for case:"
					+ "\n%10s : %s"
					+ "\n%10s : %s"
					+ "\n%10s : %s"
					+ "\n%10s : %s"
					+ "\n%10s",
				"Letters", letters,
				"Words", Arrays.toString(words),
				"Expected", expected,
				"Actual", actual,
				"");

			assertEquals(expected, actual, message);
		}
	}

	static private void generateTests()
	{
		for (int i = 0; i < 50; i++)
		{
			StringBuilder allowedCharsBuilder = new StringBuilder();
			for (int j = 0; j < 'z' - 'a'; j++)
			{
				allowedCharsBuilder.append(ThreadLocalRandom.current().nextBoolean() ? (char) ('a' + j) : "");
			}

			String[] words = new String[ThreadLocalRandom.current().nextInt(100) + 1];
			ArrayList<String> wordList = new ArrayList<>();
			Consumer<Word> addToWordlist = (word) -> wordList.add(word.word().toLowerCase());
			for (int j = 0; j < words.length; j++)
			{
				wordProvider.query()
					.attributes(Attribute.STANDARD)
					.random()
					.lengthBetween(1, 10)
					.any()
					.ifPresent(addToWordlist);
			}

			StringBuilder wordBuilder = new StringBuilder();
			words = wordList.toArray(String[]::new);
			for (int j = 0; j < words.length; j++)
			{
				wordBuilder.append("\"").append(words[j]).append("\"").append(j == (words.length - 1) ? "" : ",");
			}

			String chars = allowedCharsBuilder.toString();
			String wordz = wordBuilder.toString();
			int expected = validate(chars, words);
			System.out.printf("MAP.put(Map.entry(\"%s\",new String[]{%s}),%s);%n", chars, wordz, expected);
		}
	}

	private static int validate(String allowed, String[] words)
	{
		int count = words.length;
		int bitset = 0;
		for (char c : allowed.toCharArray())
		{
			bitset |= 1 << c - 'a';
		}

		for (String word : words)
		{
			for (char c : word.toCharArray())
			{
				if ((bitset & (1 << c - 'a')) == 0)
				{
					count--;
					break;
				}
			}
		}
		return count;
	}
}